### ISSUE TITLE
What is the intended lifetime/scope of the `PaypalServerSDKClient`?

### ISSUE THREAD

**Issue by tuespetre** [paypal/PayPal-Dotnet-Server-SDK#10]
What is the intended lifetime/scope of the `PaypalServerSDKClient`? How is it intended to be used with respect to dependency injection in an ASP.NET Core web application or .NET Core hosted worker?

**Comment by wickerpopstar** [comment]
@tuespetre We recommend using the .NET Core framework's `AddSingleton()` method for dependency injection. While we're currently developing sample applications in various Server SDK languages to demonstrate different integration approaches with the PayPal Server SDK, here's a quick snippet to show one possible way to instantiate and serve the `PaypalServerSDKClient`:
```
// Inside of Program.cs...

// Use the builder pattern provided by the .NET framework
var builder = WebApplication.CreateBuilder(args);

// Create a PaypalServerSDKClient object using your PayPal credential Client ID and Client Secret
var paypalClient = await PayPalClientConfiguration.ConfigurePayPalClientAsync(clientId, clientSecret);

// Use `AddSingleton()` to return the previously instantiated client 
builder.Services.AddSingleton(_ => paypalClient);
```

**Comment by wickerpopstar** [comment]
@tuespetre We recommend using the .NET Core framework's `AddSingleton()` method for dependency injection. While we're currently developing sample applications in various Server SDK languages to demonstrate different integration approaches with the PayPal Server SDK, here's a quick snippet to show one possible way to instantiate and serve the `PaypalServerSDKClient`:
```
// Inside of Program.cs...

// Use the builder pattern provided by the .NET framework
var builder = WebApplication.CreateBuilder(args);

// Create a PaypalServerSDKClient object using your PayPal credential Client ID and Client Secret
// This is just an example method wrapping the client creation in the SDK's setup instructions
var paypalClient = await PayPalClientConfiguration.ConfigurePayPalClientAsync(clientId, clientSecret);

// Use `AddSingleton()` to return the previously instantiated client 
builder.Services.AddSingleton(_ => paypalClient);
```

**Comment by tuespetre** [comment]
Great, thank you @wickerpopstar !
